import './styles.css';
import { initMonitoring } from './monitoring.js';
import { applyTheme } from './theme.js';
import { initDialog } from './dialogs/dialog.js';
import { initExpenseDialog } from './dialogs/expense.js';
import { initGroupDialog } from './dialogs/group.js';
import { initComposer } from './dialogs/compose.js';
import { initEvents } from './events.js';
import { initSwipe } from './swipe.js';
import { initPageSwipe } from './pageswipe.js';
import { initLive } from './live.js';
import { initAuth } from './auth.js';
import { initPhotoFallback } from './photo.js';
import { initToast } from './ui.js';
import { initServiceWorker } from './push.js';

initMonitoring();
applyTheme();
initDialog();
initExpenseDialog();
initGroupDialog();
initComposer();
initEvents();
initSwipe();
initPageSwipe();
initPhotoFallback();
initToast();
initServiceWorker();
initLive();
initAuth();
